### ISSUE TITLE
unable to compile with openwatcom 1.9

### ISSUE THREAD

**Issue by sparky4** [joncampbell123/doslib#24]
Building: dos86l
Using: /dos/fdos/watcom
Allow list: win200l win300l win312l
%write tmp.cmd -fr=nul -fo=dos86l/.obj -i=.. -i../../.. -s -zq -zl -zu -zw -zc  -nt=_TEXT -nc=CODE dboxmpi.c
/dos/fdos/watcom/h/nt/winnt.h(6332): Error! E1156: Assembler error: 'Cannot use 386 register with current CPU setting'
/dos/fdos/watcom/h/nt/winnt.h(6332): Error! E1156: Assembler error: 'Cannot use 386 operand size with current CPU setting'
/dos/fdos/watcom/h/nt/winnt.h(6333): Error! E1185: Invalid register name 'eax' in #pragma
/dos/fdos/watcom/h/nt/winnt.h(6334): Error! E1185: Invalid register name 'eax' in #pragma
/dos/fdos/watcom/h/nt/winnt.h(6336): Error! E1156: Assembler error: 'Cannot use 386 register with current CPU setting'
/dos/fdos/watcom/h/nt/winnt.h(6336): Error! E1156: Assembler error: 'Cannot use 386 operand size with current CPU setting'
/dos/fdos/watcom/h/nt/winnt.h(6337): Error! E1156: Assembler error: 'Cannot use 386 register with current CPU setting'
/dos/fdos/watcom/h/nt/winnt.h(6337): Error! E1156: Assembler error: 'Cannot use 386 addressing mode with current CPU setting'
/dos/fdos/watcom/h/nt/winnt.h(6338): Error! E1185: Invalid register name 'eax' in #pragma
/dos/fdos/watcom/h/nt/winnt.h(6339): Error! E1185: Invalid register name 'eax' in #pragma
/dos/fdos/watcom/h/nt/objidl.h(158): Warning! W135: Shift amount too large
/dos/fdos/watcom/h/nt/objidl.h(159): Warning! W135: Shift amount too large
/dos/fdos/watcom/h/nt/objidl.h(160): Warning! W135: Shift amount too large
/dos/fdos/watcom/h/nt/objidl.h(162): Warning! W135: Shift amount too large
Error(E42): Last command making (dos86l/dboxmpi.obj) returned a bad status
Error(E02): Make execution terminated

**Comment by joncampbell123** [comment]
Why is it using Windows NT headers for a 16-bit build? What build of Open Watcom are you using? It should only use headers under h/win for Windows 3.1 and Windows 3.0.

**Comment by sparky4** [comment]
no idea. i am using 1.9

**Comment by joncampbell123** [comment]
All development happens with Open Watcom 2.0, please use that.

**Comment by sparky4** [comment]
i noticed there is an issue with open watcom 2.0 on 32 bit machines! ><
not fully test this issue on 64 bit machines. also open watcom 1.9 is the latest stable release >< project 16 supports it...

**Comment by sparky4** [comment]
I cannot do a full build. but i can make small builds of componets of doslib in open watcom 1.9

**Comment by joncampbell123** [comment]
What are you using to set up the build environment?

Can you provide the output of 'env' from your shell?

**Comment by sparky4** [comment]
yes!

http://4ch.mooo.com/4/watcom/wat.sh here it is my script file i call at .bashrc with an added line of . ~/wat.sh

**Comment by joncampbell123** [comment]
No problems on my end, even using your env script.

I added it to your project, as "simulate-sparky4-watcom-env.sh". Running wbuild.sh with it shows no problems. Open Watcom v2.0.

**Comment by sparky4** [comment]
<3 ok ^^

**Comment by sparky4** [comment]
you compiled it with open watcom 1.9?

**Comment by joncampbell123** [comment]
I use Open Watcom 2.0, in fact I use the git repo on my account and compile from source.

**Comment by sparky4** [comment]
! i cloned it and compile it from source too! my computers have a 1.9 open watcom also. this is for compatibility reasons since 2.0 is not close to stable release. I can change between the two by changing the watcomver= line

watcomver="2" for open watcom 2.0
watcomver="" for open watcom 1.9

**Comment by sparky4** [comment]
i cannot compile openwatcom 2.0 well on my main pc which is using 32 bit kernel!

**Comment by joncampbell123** [comment]
Try using my branch of open-watcom-v2. I keep my copy at the last known working stable build. The main project alternates between working and broken as development progresses.

Also, mine has a nice build.sh script with instructions on-screen when finished.
